version: '3'
services:
  haproxy:
    image: haproxy
    ports:
      - "5432:5432"
      - "8081:8081"
    volumes:
      - ".:/usr/local/etc/haproxy"
      - "/dev/log:/dev/log"

  postgres1:
    image: postgres:alpine
    # ports:
    #   - "5432:5432"

  postgres2:
    image: postgres:alpine

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
