default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  port: 5432
  password:
  pool: 5
  read_timeout: 3
  connect_timeout: 3

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test